security:
    encoders:
#        Symfony\Component\Security\Core\User\User: auto
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)

        app_backend_provider:
            memory:
#                users:
#                    user:
#                        password: 'pwd"
#                        roles: ['ROLE_ADMIN','ROLE_USER']
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        all_users:
            chain:
                providers: ['app_backend_provider','app_user_provider']


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: all_users
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin/dose/days, roles: ROLE_ADMIN }
        - { path: ^/admin/dose/day, roles: ROLE_ADMIN }
        - { path: ^/admin/(product)/\d+/delete$, roles: ROLE_ADMIN }
        - { path: ^/admin/dose/(frequency|moment)/\d+/(delete|update)$, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_USER }
#        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
